### Comments after parameters are not supported — must be on a separate line
### Extra spaces between options and values are not allowed
# For more information about compatibility mode: https://github.com/hooke007/mpv_PlayKit/discussions/189
# Compatibility mode, disabled by default.
compatible_mode=no
# Compatibility mode directory, defaults to the .fonts directory inside the config directory.
compatible_dir=~~/.fonts