### Comments after parameters are not supported — must be on a separate line
### Extra spaces between options and values are not allowed
## https://mpv.io/manual/master/#commands
persist_history=no
## Persistent history (whether to retain command history), default: no
history_path=~~state/command_history.txt
## History cache path, the example shown is the default value
remember_input=yes
## Whether to retain the currently typed text when closing the console, default: yes