### Put comments on a new line. Do not put comments after parameters.
### Remove extra spaces between options and values.
## https://mpv.io/manual/master/#console

### The following options configure the built-in 'commands' script.

monospace_font=
## Set the console font. Leave empty for the system default.
font_size=24
## Set the font size.
border_size=1.65
## Set the font border width.
margin_x=-1
margin_y=-1
## Set left and bottom margins. A value of -1 matches the mpv option --osd-margin-x.
scale_with_window=auto
## <yes|no|auto> Scale the console with the window height. The 'auto' value matches the mpv option --osd-scale-by-window.

history_dedup=yes
## Remove duplicate history entries. Keep only the latest entry. Default is yes.
font_hw_ratio=auto
## Set the font height-to-width ratio. This affects the completion hint area size. Recommended range is 1.8 to 2.5. Default is auto.

### The following options configure the built-in 'select' script.

exact_match=no
## Enable exact search matching. Prefix your query with a single quote (') to temporarily enable exact matching.
case_sensitive=no
## Make exact search matching case-sensitive.
background_alpha=80
## <0-255> Set the select menu background opacity. Default is 80.
gap=0.2
## Set the gap between select menu items.
padding=10
## Set the select menu padding.
menu_outline_size=0
## Set the select menu outline thickness.
menu_outline_color="#FFFFFF"
## Set the select menu outline color. Use the format "#RRGGBB".
corner_radius=8
## Set the select menu corner radius.
focused_color="#222222"
focused_back_color="#FFFFFF"
match_color="#0088FF"
## Set the focused item color, focused item background color, and matched string color.