### Comments must be on a new line. Do not place comments after parameters.
### Do not allow extra spaces between options and values.

# Enable mpv native menu functionality. Default is yes.
use_mpv_impl=yes

# Use the default input.conf file for menu building. Default is 'default'. 
# You can manually specify another file path here.
input_conf=default

# Enable uosc-like syntax without occupying a specific hotkey. Default is yes.
uosc_syntax=yes
# Enable uosc as a fallback for specific functions. Default is no.
uosc_alt=no

# Enable title escaping. Default is yes.
escape_title=yes
# Limit the number of characters displayed in the title. Set to 0 to disable. Default is 40.
max_title_length=40
# Limit the number of items displayed in the playlist. Set to 0 to disable. Default is 20.
max_playlist_items=20