### Comments must be on a new line. Do not place comments after parameters.
### Do not allow extra spaces between options and values.

## Bind multiple keys to one function by separating them with spaces (examples show defaults).
key_move2up=UP
key_move2down=DOWN
key_move2pageup=PGUP
key_move2pagedown=PGDWN
key_move2begin=HOME
key_move2end=END
key_file_select=RIGHT
key_file_unselect=LEFT
key_file_play=ENTER
key_file_remove=BS
key_playlist_close=ESC

## Show file title whenever a new file loads. Default: no.
show_title_on_file_load=no
## Show playlist whenever a new file loads. Default: no.
show_playlist_on_file_load=no
## Automatically close the playlist after loading a new file. Default: no.
close_playlist_on_playfile=no
## Synchronize cursor state when loading files from external sources. Default: yes.
sync_cursor_on_load=yes
## Wrap cursor from the end back to the start. Default: yes.
loop_cursor=no
## Reset cursor position every time the playlist opens. Default: yes.
reset_cursor_on_open=yes
## Duration in seconds for the playlist OSD to stay visible. Default: 4.
playlist_display_timeout=4
## Number of playlist items to display before truncating. Default: 15.
showamount=15
## Truncate long filenames and set max character limit. Default: no ; 80.
slice_longfilenames=no
slice_longfilenames_amount=80

## Playlist font style using ASS tags.
## Example: {\fnUbuntu\fs10\b0\bord1} equals font=Ubuntu, size=10, bold=no, border=1.
## Refer to: https://aeg-dev.github.io/AegiSite/docs/3.2/ass_tags/
## Leave empty to use OSD settings from mpv.conf.
style_ass_tags={\rDefault\an7\fs24\b0\blur0\bord1\1c&H996F9A\3c&H000000\q2}

## Playlist header (a newline is added after the string).
## %mediatitle or %filename = Title or current file name.
## %pos = Position of current playing file.
## %cursor = Navigation position.
## %plen = Playlist length.
## %N = Newline.
playlist_header=Playlist [%cursor/%plen]

## Playlist item templates.
## %pos = File position (starts from 0).
## %name = Title or file name.
## %N = Newline.
## You can use ASS tags as shown in the examples below.
## selected_file={\c&HFF00FF&}➔ %name | Adds color to the selected file.
normal_file={\c&HFFFFFF&}□ %name
hovered_file={\c&H33FFFF&}■ %name
selected_file={\c&C1C1FF&}➔ %name
playing_file={\c&HAAAAAA&}▷ %name
playing_hovered_file={\c&H00FF00&}▶ %name
playing_selected_file={\c&C1C1FF&}➔ %name

## Indicators for when the playlist is truncated.
playlist_sliced_prefix=▲
playlist_sliced_suffix=▼