### Comments must be on a new line. Do not place comments after parameters.
### Do not allow extra spaces between options and values.
## https://mpv.io/manual/master/#positioning

toggle_align_to_cursor=no
# Determines if mouse buttons must be held to pan. 
# If 'no', dragging pans the view. 
# If 'yes', the first click makes the pan follow the cursor, and the second click disables it. 
# Default: no.

suppress_osd=no
# Determines whether to suppress OSD output of the new 'video-zoom' value when using the 'cursor-centric-zoom' command. 
# Default: no.