### Comments after parameters are not supported — must be on a separate line
### Extra spaces between options and values are not allowed

## <1|2> When to save properties. Before normal exit (default) / Based on property changes
save_mode=1

## Custom properties to record, supports multiple entries (separated by commas).
## Default value is: volume,mute
## Available properties: https://mpv.io/manual/master/#property-list
props=volume,mute

## Strict compatibility check. When enabled, if overlapping entries with --watch-later-options
## are detected, this script will automatically disable itself. Default: no
dup_block=no

## Specify the directory for the cache file. Defaults to the main config directory.
## Must be a real existing path. Relative or absolute paths are accepted. Must end with a slash.
cache_dir=~~/
