### Comments after parameters are not supported — must be on a separate line
### Extra spaces between options and values are not allowed
## https://mpv.io/manual/master/#select
## Some style customizations require referring to the script options in console.lua

history_date_format=%Y-%m-%d %H:%M:%S
# Date format for history entries. The example shown is the default value.
# This is passed to Lua's `os.date` (uses the same format as `strftime(3)`).
hide_history_duplicates=yes
# For history entries with the same path, show only the most recent one. Default: yes
