### Comments after parameters are not supported — must be on a separate line
### Extra spaces between options and values are not allowed

# Dynamic key bindings (page scrolling)
key_scroll_up=UP
key_scroll_down=DOWN
key_scroll_pgup=PGUP
key_scroll_pgdwn=PGDWN

# Path to the MediaInfo CLI executable
mediainfo_path=MediaInfo
# Whether to output full/verbose information
verbose=no
# Whether to parse network streams
network=no
# Whether to expand user properties
prop=no

# OSD output style
# Special value '_default' means automatic. Special value '_osd' uses the font from mpv's --osd-font option.
font_mono=_default
font_size=28
font_size2=20
font_size3=14
font_size4=12
indent_size=2
max_lines=22
extraspaces=24
