
backend=mpv
binpath=default
socket=
tnpath=

max_height=320
max_width=320
rescale=0
overlay_id=10

spawn_first=no
quit_after_inactivity=0
network=no
audio=no
direct_io=yes

hwdec=yes
sw_threads=2

min_duration=10
precise=0
quality=1
frequency=0.125
cache_iframe=auto
cache_max=128
be_workers=3

########################################

bat_backend=ffmpeg
bat_binpath=default
bat_path=
bat_overlay_ids=11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
bat_width=320
bat_height=320
bat_hwdec=yes
bat_threads=1
bat_be_workers=3
bat_min_duration=20
