
########################################

shader_dir=~~/shaders/
shader_exts=*,glsl,hook
shader_action_prefer=set

shader_preset_save=session
shader_cache_dir=~~/

########################################

subtext_merge=no

########################################

prop_show_values=no
prop_action_prefer=show

########################################

vcs_padding=30
vcs_tiles=12
vcs_chapter_mode=no
