### Comments after parameters are not supported — must be on a separate line
### Extra spaces between options and values are not allowed

## URL parsing blacklist. Empty by default.
## Format explanation: https://mpv.io/manual/master/#options-exclude
## Example value: "%.avi$|%.flac$|%.flv$|%.mp3$|%.m3u$|%.m3u8$|%.m4a$|%.m4v$|%.mkv$|%.mp4$|%.ts$|%.VOB$|%.wav$|%.webm$|%.wmv$"
## Recommended to use when try_ytdl_first=yes to reasonably speed up URL resolution.
exclude=

## URL parsing whitelist. Same format as above.
## The example shown is the default value.
## Even when try_ytdl_first=no, ytdlp will still be used to parse the following URLs.
include=^%w+%.youtube%.com/|^youtube%.com/|^youtu%.be/|^%w+%.twitch%.tv/|^twitch%.tv/

## Prefer trying to parse URLs with ytdlp first. Default: no
try_ytdl_first=no

## Allow switching tracks between sources (disabled by default for performance reasons)
use_manifests=no
## See https://mpv.io/manual/master/#options-all-formats for explanation
all_formats=no
force_all_formats=yes
## <all|best|none (default)> Add thumbnails as video tracks
thumbnails=none

## Requires yt-dlp.exe / youtube-dl.exe to be in the PATH environment variable,
## or placed in the same directory as mpv.exe. Default value is empty.
ytdl_path=
